services:
  router:
    image: ghcr.io/wundergraph/cosmo/router:latest
    ports:
      - "3002:3002"
      - "8088:8088"
    environment:
      - LISTEN_ADDR=0.0.0.0:3002
    volumes:
      - ./config.yaml:/config.yaml
      - ./router.json:/router.json
